config/routes.rb
  Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :bookings, only: [:new, :create]
  end
  get 'search', to: 'flats#search'
  resources :bookings, only: [:show, :index, :destroy]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  enum status: { pending: 0, confirmed: 1, cancelled: 2 }
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many_attached :photos
  validates :address, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :capacity, presence: true, numericality: { greater_than: 0 }
  #serialize :available_days, Array
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :flats, dependent: :destroy
  has_many :bookings
  validates :email, uniqueness: true
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_flat, only: %i[new create update]

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: 'Booking was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to @booking, notice: 'Booking was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_url, notice: 'Booking was successfully destroyed.'
  end

  private

  def booking_params
    params.require(:booking).permit(:check_in, :check_out, :status, :user_id, :flat_id)
  end

  def set_flat
    @flat = Flat.find(params[:flat_id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
   @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user # Here we assign the user_id parameter as the current user that is adding the flat
    if @flat.save
      redirect_to flats_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    redirect_to flats_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.bookings.destroy_all
    @flat.destroy
    redirect_to flats_path, status: :see_other
  end

  def search

    @flats = Flat.all
    if params[:destination].present?
      @flats = @flats.where(address: params[:destination])
    end
    @check_in = @flats.where(available_start: params[:date_in])
    @check_out = @flats.where(available_end: params[:date_out])

    if @flats.where(available_start: params[:date_in]).present? &&
       @flats.where(available_end: params[:date_out]).present?
      @available = available_days(@flats.where(available_start: params[:date_in]), @flats.where(available_end: params[:date_out]))
    else
      @available = []

    end

  end

  end

  private

  def flat_params
    params.require(:flat).permit(:address, :price, :capacity, :user_id, :reserved, :title, :description, :image_url, :available_start, :available_end, photos: [])
  end


def available_dates(check_in, check_out)
  check_in_date = Date.parse(check_in)
  check_out_date = Date.parse(check_out)

  @flat = Flat.where("check_in < ? AND check_out > ?", check_out_date, check_in_date)

  if @flat.exists?
    return []
  else
    return [check_in_date, check_out_date]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
    @flats = Flat.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= form_with(model: @booking, local: true) do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
        <% @booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :check_in %>
    <%= form.datetime_select :check_in %>
  </div>

  <div class="field">
    <%= form.label :check_out %>
    <%= form.datetime_select :check_out %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :flat_id %>
    <%= form.collection_select :flat_id, Flat.all, :id, :address %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit "Update Booking" %>
  </div>
<% end %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<div class="container"> <!--Contenedor de todo el contenido-->
  <div class="d-flex justify-content-between"> <!--Contenedor del titulo con sus botones-->
    <h1 class="mt-3">My Bookings</h1>
  </div>
  <div class="container mt-3">
    <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"><i class="fa-solid fa-house"></i> Booking ID</th>
        <th scope="col"><i class="fa-solid fa-location-dot"></i> Check-In</th>
        <th scope="col"><i class="fa-solid fa-location-dot"></i>Check-Out</th>
        <th scope="col"><i class="fa-solid fa-address-book"></i> Flat Address</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    <% cont = 1 %>
    <% if current_user.bookings.present? %>
      <% @bookings.each do |booking| %>
        <% if booking.user == current_user %>
          <tr>
            <th scope="row" style="color: #818589"><div class="text-center"> <%= cont %><div></th>
            <td style="color: #818589"><%= booking.id %></td>
            <td style="color: #818589"><%= booking.check_in %></td>
            <td style="color: #818589">$ <%= booking.check_out %></td>
            <td style="color: #818589"><%= booking.flat.address %></td>
            <td><%= link_to booking_path(booking) do %><i class="fa-solid fa-eye" style="margin: 5px"></i><% end %><%= link_to booking_path(booking), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %><i class="fa-solid fa-trash" style="margin: 5px"></i><% end %></td>
            <% cont += 1 %>
          </tr>
        <% end %>
      <% end %>
      <% else %>
        <tr>
          <td colspan="7" style="text-align: center">No Bookings created<td>
        </tr>
      <% end %>
      </tbody>
      </table>
  </div>
<div class="d-grid gap-2 d-md-block">
  <%= link_to 'Back Home', root_path, class:'btn btn-outline-primary m-3'%>
</div>
</div>

app/views/bookings/new.html.erb
<div class="container w-50 shadow border p-3 mt-5">
  <h1>New Booking</h1>

  <%= simple_form_for [@flat, @booking] do |f| %>
    <%= f.input :check_in, label: 'Choose an initial date for reservation:', html5: true%>
    <%= f.input :check_out, label: 'Choose an ending date for reservation:', html5: true%>
    <%= f.button :submit, "Create Booking", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container w-50 shadow border p-4 mt-2 mb-5">
      <div class="container"> <!--CONTENEDOR DE LAS FOTOGRAFIAS-->
        <h1 class="my-3" style="font-family: Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif;">Booking  #<%= @booking.id %></h1>
        <h2 class="my-3" style="font-family: Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif;"><i class="fa-solid fa-house" style="color: rgb(243, 35, 156)"></i> <%= @booking.flat.title %></h2>
          <div class="row d-flex justify-content-center">
            <% @booking.flat.photos.first %>
                <div class="col-12">
                  <div>
                    <%= cl_image_tag @booking.flat.photos.first.key, class:"img-fluid", width: "100%" %>
                  </div>
                </div>
          </div>
          <div class="d-flex justify-content-between mt-3">
            <div>
            <h4 style="color: rgb(243, 35, 156)"><strong>Check-In</strong></h4>
            <%= @booking.check_in %>
            </div>
            <div>
            <h4 style="color: rgb(243, 35, 156)"><strong>Check-Out</strong></h4>
            <%= @booking.check_out %>
            </div>
          </div>
          <hr>
          <h3 class="mt-3"><strong>Description</strong></h3>
          <p><%= @booking.flat.description %></p>
          <hr>
          <h3 class="mt-3"><strong>Address</strong></h3>
          <p><%= @booking.flat.address %></p>
          <hr>
          <h3 class="mt-3"><strong>Guests</strong></h3>
          <p><%= @booking.flat.capacity %></p>
          <div class="d-grid gap-2">
            <button style="background-color: rgb(243, 35, 156); border: 2px solid rgb(243, 35, 156); border-radius: 10px"> <%= link_to 'Back', bookings_path, style:'color: white; text-decoration: none;' %></button>

          </div>

      </div>
      </div>
</div>

<%= link_to 'Back', bookings_path %> |

app/views/flats/_row.html.erb
<% @bookings.each do |booking| %>
  <tr>
    <td scope="col"> Booking ID <%=  %></th>
    <td scope="col"> Check-In <%=  %></th>
    <td scope="col"> Check-Out <%=  %></th>
    <td scope="col"> Guest <%=  %></th>
  </tr>
  <tr>
    <td><%= booking.id %></td>
    <td><%= booking.check_in %></td>
    <td><%= booking.check_out %></td>
    <td><%= booking.user.first_name %> <%= booking.user.last_name %></td>
  </tr>
<% end %>

app/views/flats/edit.html.erb
<div class="container w-50 shadow border p-3 mt-5">
  <h1 class="my-3" style="font-family: Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif;">Edit your flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :address, label: 'Address:' %>
    <%= f.input :price, label: 'Price' %>
    <%= f.input :capacity, label: 'Capacity' %>
    <%= f.input :title, label: 'Title' %>
    <%= f.input :description, label: 'Description' %>
    <%= f.input :available_start, label: 'Initial date the flat will be available for reservation', html5: true %>
    <%= f.input :available_end, label: 'Final date the flat will be available for reservation', html5: true %>
    <div class="container">
      <div class="row mb-3">
        <div class="col-sm">
          <%= cl_image_tag @flat.photos.first.key, height: 200, width: 200, crop: :fill, class:"img-fluid" %>
        </div>
        <div class="col-sm">
          <%= cl_image_tag @flat.photos.second.key, height: 200, width: 200, crop: :fill, class:"img-fluid" %>
        </div>
        <div class="col-sm">
          <%= cl_image_tag @flat.photos.last.key, height: 200, width: 200, crop: :fill, class:"img-fluid" %>
        </div>
      </div>
    </div>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <div class="d-grid gap-2 d-md-block">
      <%= f.button :submit, "Save Flat", class: 'btn btn-primary'%>
      <%= link_to 'Cancel', flats_path, class:'btn btn-outline-primary m-3'%>
    </div>
  <% end %>
</div>

app/views/flats/index.html.erb
<div class="container"> <!--Contenedor de todo el contenido-->
  <div class="d-flex justify-content-between"> <!--Contenedor del titulo con sus botones-->
    <h1 class="mt-3">My Flats</h1>
    <%= link_to '+ Add Flat', new_flat_path, class:'btn btn-outline-primary m-3'%>
  </div>
  <div class="container mt-3">
    <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col"><i class="fa-solid fa-house"></i> Title</th>
        <th scope="col"><i class="fa-solid fa-location-dot"></i> Address</th>
        <th scope="col"><i class="fa-solid fa-money-bill"></i> Price</th>
        <th scope="col"><i class="fa-solid fa-users"></i> Capacity</th>
        <th scope="col"><i class="fa-solid fa-hourglass-start"></i> Available from</th>
        <th scope="col"><i class="fa-solid fa-hourglass-end"></i> Available until</th>
        <th scope="col">Actions</th>
      </tr>
    </thead>
    <tbody>
    <% cont = 1 %>
    <% if current_user.flats.present? %>
      <% @flats.each do |flat| %>
        <% if flat.user == current_user %>
          <tr>
            <th scope="row" style="color: #818589"><div class="text-center"> <%= cont %><div></th>
            <td style="color: #818589"><%= flat.title %></td>
            <td style="color: #818589"><%= flat.address %></td>
            <td style="color: #818589">$ <%= flat.price %></td>
            <td style="color: #818589"><%= flat.capacity %></td>
            <td style="color: #818589"><%= flat.available_start %></td>
            <td style="color: #818589"><%= flat.available_end %></td>
            <td><%= link_to flat_path(flat) do %><i class="fa-solid fa-eye" style="margin: 5px"></i><% end %><%= link_to edit_flat_path(flat) do %><i class="fa-solid fa-pen-to-square" style="margin: 5px"></i><% end %><%= link_to flat_path(flat), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } do %><i class="fa-solid fa-trash" style="margin: 5px"></i><% end %></td>
            <% cont += 1 %>
          </tr>
        <% end %>
      <% end %>
      <% else %>
        <tr>
          <td colspan="7" style="text-align: center">No flats created<td>
        </tr>
      <% end %>
      </tbody>
      </table>
  </div>
<div class="d-grid gap-2 d-md-block">
  <%= link_to 'Back Home', root_path, class:'btn btn-outline-primary m-3'%>
</div>
</div>

app/views/flats/new.html.erb
<div class="container w-50 shadow border p-3 mt-5">
  <h1 class="my-3" style="font-family: Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif;">Start adding your flat</h1>
  <%= simple_form_for @flat do |f| %>
    <%= f.input :address, label: 'Address:' %>
    <%= f.input :price, label: 'Price' %>
    <%= f.input :capacity, label: 'Capacity' %>
    <%= f.input :title, label: 'Title' %>
    <%= f.input :description, label: 'Description' %>
    <%= f.input :available_start, label: 'Initial date the flat will be available for reservation', html5: true %>
    <%= f.input :available_end, label: 'Final date the flat will be available for reservation', html5: true %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <div class="d-grid gap-2 d-md-block">
      <%= f.button :submit, "Save Flat", class: 'btn btn-primary'%>
      <%= link_to 'Cancel', flats_path, class:'btn btn-outline-primary m-3'%>
    </div>
  <% end %>
</div>

app/views/flats/search.html.erb
<div class="container-flex">
    <div class="row">
      <% if @flats.any? %>
        <% @flats.each do |flat| %>
          <div class="col-md-4 flex-cards">
            <div class="card mb-4 shadow-sm">
              <% if flat.image_url.present? %>
                <!-- Agregar la imagen desde la URL almacenada en la base de datos -->
                <img src="<%= flat.image_url %>" class="card-img-top" alt="Flat Image">
              <% else %>
                <!-- Si no hay una imagen disponible, puedes mostrar una imagen de marcador de posición -->
                <img src="https://via.placeholder.com/350x200" class="card-img-top" alt="Placeholder Image">
              <% end %>
              <div class="card-body">
                <h5 class="card-title"><%= flat.title %></h5>
                <p class="card-text"><%= flat.description %></p>
                <p class="card-text text-muted">Price: <%= number_to_currency(flat.price) %></p>
                <%= link_to 'View Flat', flat_path(flat), class: 'btn btn-secondary' %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>No flats available at the moment.</p>
      <% end %>
    </div>
</div>

app/views/flats/show.html.erb
<div class="container w-80 shadow border p-4 mt-2 mb-5">
      <div class="container"> <!--CONTENEDOR DE LAS FOTOGRAFIAS-->
        <h1 class="my-3" style="font-family: Circular, -apple-system, BlinkMacSystemFont, Roboto, Helvetica Neue, sans-serif;"><i class="fa-solid fa-house" style="color: rgb(243, 35, 156)"></i> <%= @flat.title %></h1>
          <div class="row d-flex justify-content-center">
            <% @flat.photos.first %>
                <div class="col-8">
                  <div>
                    <%= cl_image_tag @flat.photos.first.key, class:"img-fluid" %>
                  </div>
                </div>
                <div class="col-4">
                  <div class="col-6 mb-2">
                      <%= cl_image_tag @flat.photos.first.key, class:"img-fluid", size:"250x250" %>
                  </div>
                  <div class="col-6">
                      <%= cl_image_tag @flat.photos.first.key, class:"img-fluid", size:"255x250" %>
                  </div>
                </div>
          </div>
      </div>
      <div class="row me-3 mt-4">
        <div class="col ms-3">
          <h3><strong>Flat in <%= @flat.address %></strong></h3>
          <h4>About this place</h4>
          <p><%= @flat.description %></p>
          <hr>
          <p class="mb-1"><strong>Stay with </strong></p>
          <p><%= @flat.user.email.split('@').first %></p>
            <%= link_to "Book Now", new_flat_booking_path(@flat), class:'btn pink-btn btn-lg mt-4'%>
            <%= link_to 'Back', root_path, class:'btn pink-btn btn-lg mt-4'%>
        </div>
        <div class="col ms-3">
        <h4>$ <%= @flat.price %></h4>
              <table class="table table-bordered rounded">
              <tbody>
                <colgroup>
                  <col span="1" style="width: 50%">
                  <col span="1" style="width: 50%">
                </colgroup>
                <tr>
                  <th scope="col" style="color: #f234b1">CHECK-IN</th>
                  <th scope="col" style="color: #f234b1">CHECK-OUT</th>
                </tr>
                <tr>
                  <td style="color: #818589"><%= @flat.available_start %></td>
                  <td style="color: #818589"><%= @flat.available_end %></td>
              </tbody>
            </table>
            <th scope="col"><i class="fa-solid fa-users"></i><strong> CAPACITY:</strong> <%= @flat.capacity %></th>
        </div>
      </div>
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reservify</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
     <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
   <%=render "shared/navbar_bottom" %>
   <%=render "shared/footer" %>

   <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-container">
  <div class="banner-image" style="background-image: url('https://images.pexels.com/photos/5273346/pexels-photo-5273346.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1');">
    <div class="banner-text">
      <div class="banner-top-left">
        <h1 class="my-4">Welcome to <span class="title">Reservify</span></h1>
      </div>
      <div class="banner-center wheat-color">
        <h2>Discover Your Next Stay</h2>
        <p>Find the best flats for your next trip.</p>
      </div>
    </div>
  </div>
</div>

<div class="container w75 my-4">
  <%= render 'shared/search_bar' %>
</div>

<div class="container mb-5">
  <div class="row">
    <% if @flats.any? %>
      <% @flats.each do |flat| %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 mb-4">
          <div class="card mb-4 shadow-sm h-100 rounded" style="min-height: 400px;">
            <% if flat.photos.present? %>
              <%= image_tag flat.photos.first, class: "card-img-top img-fluid rounded-top", style: "height: 155px; object-fit: cover;" %>
            <% else %>
              <img src="https://via.placeholder.com/350x200" class="card-img-top" alt="Placeholder Image">
            <% end %>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title fw-bold"><%= flat.title %></h5>
              <p class="card-text"><%= flat.description %></p>
              <p class="card-text text-muted mt-auto">Price: <%= number_to_currency(flat.price) %></p>
              <%= link_to 'View Flat', flat_path(flat), class: 'btn btn-secondary mt-2' %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>No flats available at the moment.</p>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
    <div class="container text-center">
      <a href="https://facebook.com" class="text-white mx-2" target="_blank">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="https://twitter.com" class="text-white mx-2" target="_blank">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="https://instagram.com" class="text-white mx-2" target="_blank">
        <i class="fab fa-instagram"></i>
      </a>

    </div>
  </footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%=  image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.present?  %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% else  %>
              <%= image_tag "user-logo.png", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My flats", flats_path, class: "dropdown-item" %>
              <%= link_to "My bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_bottom.html.erb
<nav class="navbar-bottom">
  <%= link_to flats_path, class: 'nav-link-bottom' do %>
    <i class="fas fa-home"></i>
    <span class="nav-text-bottom">Home</span>
  <% end %>

  <a href="#" class="nav-link-bottom">
    <i class="fas fa-search"></i>
    <span class="nav-text-bottom">Search</span>
  </a>

  <%= link_to new_flat_path, class: 'nav-link-bottom' do %>
    <i class="fa-solid fa-plus"></i>
    <span class="nav-text-bottom">Add</span>
  <% end %>

  <%= link_to edit_user_registration_path, class: 'nav-link-bottom' do %>
    <i class="fas fa-user"></i>
    <span class="nav-text-bottom">Profile</span>
  <% end %>
</nav>

app/views/shared/_search_bar.html.erb
<%= form_with(url: search_path, method: "get", local: false, class: "search-bar") do |f| %>
  <div class="search-field">
    <%= label_tag :destination do %>
      <i class="fas fa-search"></i>
    <% end %>
    <%= text_field_tag :destination, params[:destination], placeholder: "Where are you going?" %>
  </div>

  <div class="search-field">
    <%= label_tag :dates do %>
      <i class="fas fa-calendar-alt"></i>

    <% end %>
     <%= text_field_tag :date_in, params[:dates], placeholder: "Check in ",  data: {controller: 'datepicker'} %>
     <%= text_field_tag :date_out, params[:dates], placeholder: "Check out ",  data: {controller: 'datepicker'} %>

  </div>

  <div class="search-field">
    <%= label_tag :guests do %>
      <i class="fas fa-user-friends"></i>
    <% end %>
    <%= text_field_tag :guests, params[:guests], placeholder: "Guests" %>
  </div>

  <%= submit_tag "Search", class: "search-button" %>
<% end %>